### ISSUE TITLE
click error

### ISSUE THREAD

**Issue by Kkap-soul** [ASangarin/Breaker#1]
if i click any block on survival mode, error occur

![image](https://user-images.githubusercontent.com/85030527/122792119-cf7f1f00-d2f4-11eb-9953-0d6594d1c158.png)

**Comment by ASangarin** [comment]
What Minecraft version are you using?

**Comment by Kkap-soul** [comment]
![image](https://user-images.githubusercontent.com/85030527/122970782-4685e780-d3c9-11eb-86b8-deebb761b7c2.png)
yes I am using 1.12
but you wrote 1.12 is tested version
is there really no way?
